services:
  RenjiNSK\DiscordHandlerBundle\Services\DiscordMonologHandlerService:
    arguments:
      - 'webhook_url'
      - 'name'
      - 'subName'
      - 'level'
      - 'bubble'
    calls:
      - method: setEnvironment
        arguments:
          - '%kernel.environment%'
